# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

# MAGIC %pip install stravalib

# COMMAND ----------

import time
from stravalib import Client

ACCESS_TOKEN = dbutils.secrets.get(scope = "strava", key = "access_token")
REFRESH_TOKEN = dbutils.secrets.get(scope = "strava", key = "refresh_token")
EXPIRES_AT = 1754914810

# --- Client Strava ---
client = Client(
    access_token=ACCESS_TOKEN,
    refresh_token=REFRESH_TOKEN,
    token_expires=EXPIRES_AT,
)

# --- Exemple d'appel API ---
athlete = client.get_athlete()
print(f"Hi, {athlete.firstname} Welcome to stravalib!")
print("expires_at =", client.token_expires)

# COMMAND ----------

# MAGIC %md
# MAGIC # Secrets

# COMMAND ----------

import time

from databricks.sdk import WorkspaceClient

w = WorkspaceClient()

key_name = "###"

scope_name = "strava"

string_value = "###"

w.secrets.put_secret(scope=scope_name, key=key_name, string_value=string_value)

# COMMAND ----------

scrts = w.secrets.list_secrets(scope=scope_name)
scrts
